import type { Metadata } from "next";
import "./globals.css";

import TopNav from "@/app/components/TopNav";
import Footer from "@/app/components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayoutRoute({
  children,
}: {
  readonly children: React.ReactNode;
}) {
  return (
    <html lang="en" data-theme="dark">
      <body className="wrapper">
        <TopNav />
        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
